/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.kakao.bank.alert.server.api

import com.kakao.bank.alert.server.utils.StringUtils
import org.apache.commons.text.WordUtils
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.autoconfigure.domain.EntityScan
import org.springframework.boot.runApplication
import org.springframework.data.jpa.repository.config.EnableJpaRepositories

@EntityScan(basePackages = ["com.kakao.bank.alert.server.domain"])
@EnableJpaRepositories(basePackages = ["com.kakao.bank.alert.server.domain"])
@SpringBootApplication(scanBasePackages = ["com.kakao.bank.alert"])
class Application

fun main(args: Array<String>) {
    val tokens = StringUtils.split(MessageUtils.getMessage())

    println(WordUtils.capitalize(tokens))

    runApplication<Application>(*args)
}
