/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.kakao.bank.alert.server.api

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World!"
    }
}
