/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.kakao.bank.alert.server.utils

class StringUtils {
    companion object {
        fun split(source: String): String {
            return "$source Test"
        }
    }
}
